"""NAPSEQ reference implementation (Python).

Wire format v7 (block mode) — see ``SPEC.md`` at repo root. The wire format
and the Python SDK version are versioned independently: this module's public
API may change in backward-incompatible ways while keeping a given wire
version's byte layout stable.

**v7 supersedes v6** as of the CVF1 audit fix (see ``docs/CAVEATS.md``):
block-mode tokens are now serialised as fixed-width 8-byte big-endian fields
(``_fixed_encode_tokens``) instead of variable-length LEB128 varints
(``_b128_encode_tokens``). Under v6, a token's LEB128 byte-length grows with
its magnitude (which is a function of the plaintext codepoint value), so the
serialised blob length — and hence the final ciphertext length — leaked
information about plaintext content even between messages of equal padded
length. This broke the IND-CPA hiding argument (Theorem 1 of
``docs/napseq-eprint-preprint.tex``), which assumed equal padded length
implies equal blob byte-length. v7's fixed-width encoding makes blob length a
function only of the *number* of tokens (itself a function of the padded
codepoint count and the HMAC-derived, content-independent noise schedule),
never of codepoint values, restoring that argument. ``decrypt_bytes`` /
``decrypt_str`` still read v6 ciphertexts via the explicit
``legacy_v6_varint=True`` opt-in.

Known leakage and caveats (see ``docs/CAVEATS.md`` for full triage):

* **Key ordering is a security parameter.** ``[k0, k1, …]`` and
  ``[k1, k0, …]`` are *distinct* keys that produce non-interoperable
  ciphertexts. Callers must preserve element order when storing or
  transmitting key material.
* **Length-bucket leakage.** ``encrypt_bytes`` / ``encrypt_str`` pad plaintext
  to the next power-of-two block size (min 16). The ciphertext therefore
  reveals which power-of-two bucket the plaintext length falls into, and
  nothing more: at most ``log2(13) ~= 3.70`` bits per message. v8 callers
  needing *zero* length leakage pass ``pad_profile=("frame", F)`` to
  ``encrypt_bytes_v8`` / ``encrypt_str_v8``; v7 callers must layer a
  fixed-frame transport on top.
* **16-bit length cap.** Block-mode plaintext is capped at
  ``MAX_PLAINTEXT_CODEPOINTS`` (65535) by the 2-codepoint length prefix in
  ``_pad_message``. Raising the cap requires a future wire-format bump
  (deferred; independent of the v7/CVF1 fix).
* **Streaming RUP.** ``decrypt_stream`` releases plaintext before the auth
  tag is verified. It is gated behind
  ``enable_unauthenticated_streaming=True``; prefer ``decrypt_stream_strict``
  which buffers all plaintext and verifies the tag before returning.
* **Streaming content-length correlation (CVF1, not yet fixed for streaming).**
  ``encrypt_stream`` / ``encrypt_stream_ae`` still serialise tokens as LEB128
  varints. Streaming mode already discloses the exact plaintext length (no
  padding is applied there), so this does not break an IND-CPA claim the way
  the block-mode leak did, but the same magnitude-dependent byte-length
  pattern is present. Tracked as a follow-up to CVF1.
* **Legacy v2/v3/v5/v6 formats** are read-only and require explicit opt-in
  via ``allow_legacy_unauthenticated=True`` (v2/v3/v5) or
  ``legacy_v6_varint=True`` (v6).
"""

import math
import os
import secrets
import hmac
import hashlib
import base64
import warnings
from collections.abc import Generator, Iterable
from typing import Union


_NONCE_SIZE = 16
_TAG_SIZE = 32

#: Width of the AAD length prefix in the v8 block-mode domains ``0x03``
#: (auth tag) and ``0x0A`` (synthetic nonce). v7 and the streaming-AE
#: domains keep the legacy 4-byte prefix and stay byte-compatible.
_AAD_LEN_WIDTH_V8 = 8

#: Endpoints of the v8 noise-threshold interval, as fixed-width 64-bit
#: integers (docs/napseq-eprint-v3.tex Section ``noiseprob``).  The v8 noise
#: schedule is specified entirely over these integers so that theta(N) is
#: bit-identical across every conforming implementation; the legacy v7 path
#: keeps the original IEEE-754 formulation and stays byte-compatible.
_THETA_MIN = (75 * (1 << 64)) // 100
_THETA_MAX = (99 * (1 << 64)) // 100

#: Maximum plaintext length (in codepoints) accepted by the block-mode
#: ``encrypt_bytes`` / ``encrypt_str`` API. Imposed by the 2-codepoint
#: big-endian length prefix written by ``_pad_message``. Raising this cap
#: requires a wire-format change (v7, deferred per ROADMAP.md §3.7).
MAX_PLAINTEXT_CODEPOINTS = 0xFFFF

#: Minimum prime value accepted as a key element.  Primes below this threshold
#: provide negligible per-element security (e.g. p=2 gives 1-bit residue space).
#: Production keys generated by :func:`generate_prime_numbers` use the default
#: range [1_000_000, 9_900_000] and always satisfy this bound.
MIN_KEY_PRIME = 1_000_000

#: Upper bound of the normative prime interval P = [MIN_KEY_PRIME, MAX_KEY_PRIME]
#: specified in docs/napseq-eprint-v3.tex §Notation.  This bound constrains key
#: *generation* only; validation and decryption accept any prime >= MIN_KEY_PRIME
#: so that keys generated before this bound was tightened remain usable.
MAX_KEY_PRIME = 9_900_000

#: Minimum recommended number of prime key elements.  Inherited from the v7
#: single-secret schedule, in which H_inf(key) entered the IND-CPA bound and
#: K < 7 gave H_inf(key) < 128 bits.  Under the v8/v3 schedule sk is sampled
#: independently and is the sole HMAC key, so no theorem depends on
#: H_inf(key) and K is an interoperability parameter rather than a security
#: one (docs/napseq-eprint-v3.tex, Remark ``key-roles``).  The warning is
#: retained for v7 callers only.
MIN_KEY_COUNT = 7


def _warn_if_weak_key_count(count: int) -> None:
    """Warn (not raise) if *count* is below :data:`MIN_KEY_COUNT`.

    Relevant to the v7 single-secret schedule only.  Under v8 the prime tuple
    never keys an HMAC call, so K carries no security-theorem-driven minimum
    (docs/napseq-eprint-v3.tex, Remark ``key-roles``).
    """
    if count < MIN_KEY_COUNT:
        warnings.warn(
            f"Key element count K={count} is below the recommended minimum "
            f"of {MIN_KEY_COUNT}. Under the v7 single-secret schedule this "
            "gives H_inf(key) < 128 bits, making offline exhaustive key "
            "search feasible. Under v8 no theorem depends on H_inf(key) "
            "(docs/napseq-eprint-v3.tex, Remark 'key-roles'), so this "
            "warning is advisory for v8 callers.",
            category=UserWarning,
            stacklevel=3,
        )


def _secure_float() -> float:
    """Cryptographically secure float in [0, 1) via os.urandom."""
    return int.from_bytes(os.urandom(8), 'big') / (2 ** 64)


def _secure_randint(low: int, high: int) -> int:
    """Cryptographically secure integer in [low, high) via secrets."""
    span = high - low
    if span <= 0:
        raise ValueError(f"Invalid range [{low}, {high})")
    return secrets.randbelow(span) + low


def is_prime(n: int) -> bool:
    """Check if a number is prime."""
    if n < 2:
        return False
    if n == 2:
        return True
    if n % 2 == 0:
        return False
    for i in range(3, int(math.sqrt(n)) + 1, 2):
        if n % i == 0:
            return False
    return True


def generate_prime_numbers(count: int = 10,
                           min_val: int = MIN_KEY_PRIME,
                           max_val: int = MAX_KEY_PRIME) -> list[int]:
    """Generate *count* distinct primes drawn uniformly from [min_val, max_val].

    The default range is the normative interval P = [1 000 000, 9 900 000] of
    docs/napseq-eprint-v3.tex §Notation, which contains exactly 579 947 primes
    (verified by sieve of Eratosthenes).  A 10-element key (ordered, no
    repetition) from this range gives a key space of
    P(579 947, 10) = 2^191.46 (= 2^95.73 post-Grover).

    Note that no theorem in the v8/v3 security analysis depends on
    H_inf(key); see MIN_KEY_COUNT and the paper's Remark ``key-roles``.
    """
    _warn_if_weak_key_count(count)
    primes: list[int] = []
    max_attempts = (max_val - min_val) * 4
    attempts = 0
    while len(primes) < count and attempts < max_attempts:
        num = secrets.randbelow(max_val - min_val + 1) + min_val
        if is_prime(num) and num not in primes:
            primes.append(num)
        attempts += 1
    if len(primes) < count:
        raise RuntimeError(
            f"Could not find {count} distinct primes in [{min_val}, {max_val}] "
            f"after {max_attempts} attempts — widen the range."
        )
    return primes


# ─── HMAC session helpers ────────────────────────────────────────────────────

def _validate_nonce(nonce: bytes) -> None:
    if not isinstance(nonce, (bytes, bytearray)):
        raise TypeError(f"Nonce must be bytes, got {type(nonce).__name__!r}.")
    if len(nonce) != _NONCE_SIZE:
        raise ValueError(
            f"Nonce must be exactly {_NONCE_SIZE} bytes, got {len(nonce)}."
        )


def _validate_cypher(cypher: list[int]) -> None:
    if not isinstance(cypher, list):
        raise TypeError(f"Cypher must be a list, got {type(cypher).__name__!r}.")
    for i, token in enumerate(cypher):
        if not isinstance(token, int) or isinstance(token, bool):
            raise TypeError(
                f"Cypher token at index {i} ({token!r}) is not an integer."
            )
        if token < 0:
            raise ValueError(
                f"Cypher token at index {i} ({token!r}) is negative; "
                "all tokens must be non-negative integers."
            )


def _validate_key(key: list[int]) -> None:
    """Validate that *key* is a non-empty list of distinct primes > 1.

    Raises ValueError if the key is empty, contains a composite or unit
    element, or contains duplicate elements.  Call this at the entry point
    of every public API that accepts a key so that callers get a clear error
    rather than a ZeroDivisionError or a silent security degradation.
    """
    if not key:
        raise ValueError("Key must be a non-empty list of integers.")
    _warn_if_weak_key_count(len(key))
    seen: set[int] = set()
    for i, k in enumerate(key):
        if not is_prime(k):
            raise ValueError(
                f"Key element at index {i} ({k!r}) is not prime. "
                "All key elements must be prime integers greater than 1."
            )
        if k < MIN_KEY_PRIME:
            raise ValueError(
                f"Key element at index {i} ({k!r}) is below the minimum of "
                f"{MIN_KEY_PRIME}. Use generate_prime_numbers() to generate "
                "a secure key."
            )
        if k in seen:
            raise ValueError(
                f"Key element {k!r} at index {i} is a duplicate. "
                "All key elements must be distinct."
            )
        seen.add(k)


def _key_bytes(key: list[int]) -> bytes:
    """Serialise key list to fixed-width bytes for HMAC keying."""
    return b''.join(k.to_bytes(5, 'big') for k in key)


def _is_noise_pos(kb: bytes, nonce: bytes, ct_pos: int, noise_p: float) -> bool:
    """Return True iff ciphertext position *ct_pos* should hold a noise token.

    This decision is made deterministically via HMAC-SHA256 keyed with the
    serialised encryption key, so an attacker without the key cannot distinguish
    noise positions from real-token positions — eliminating the divisibility
    oracle that made the original design vulnerable.
    """
    digest = hmac.new(kb,
                      b'\x00' + nonce + ct_pos.to_bytes(5, 'big'),
                      hashlib.sha256).digest()
    val = int.from_bytes(digest[:8], 'big') / 2**64   # uniform in [0, 1)
    return val < noise_p


def _derive_addend(kb: bytes, nonce: bytes, real_idx: int,
                   key_element: int) -> int:
    """Return a per-real-token addend in [1, key_element − 1].

    Because *key_element* is prime every value in (0, key_element) is coprime
    to it.  The addend is derived from HMAC(key, nonce, real_idx), so without
    the key it is computationally unpredictable.  Adding it to ``char × key[i]``
    makes real tokens non-divisible by any key element and statistically unique
    even for repeated characters — defeating frequency analysis and all
    divisibility-based key-recovery attacks.
    """
    digest = hmac.new(kb,
                      b'\x01' + nonce + real_idx.to_bytes(5, 'big'),
                      hashlib.sha256).digest()
    return (int.from_bytes(digest[:4], 'big') % (key_element - 1)) + 1


def _derive_noise_char(kb: bytes, nonce: bytes, ct_pos: int) -> int:
    """Return a noise 'character' codepoint in [32, 127] derived from HMAC.

    Domain separator ``b'\\x04'`` isolates this from all real-token derivations.
    Noise tokens are generated as ``noise_c * k + noise_addend`` — the same
    formula used for real tokens — so they are never exact multiples of k and
    therefore can never equal ``known_cp * k`` for any integer ``known_cp``.
    This defeats the known-plaintext divisibility attack that targeted old noise
    tokens whose range ``[k*32, k*129)`` could contain the value ``known_cp*k``.
    """
    digest = hmac.new(kb,
                      b'\x04' + nonce + ct_pos.to_bytes(5, 'big'),
                      hashlib.sha256).digest()
    return (int.from_bytes(digest[:4], 'big') % 96) + 32   # [32, 127]


def _derive_noise_token_addend(kb: bytes, nonce: bytes, ct_pos: int,
                               key_element: int) -> int:
    """Return a per-noise-token addend in [1, key_element − 1].

    Domain separator ``b'\\x05'`` isolates this from real-token addend
    derivation (domain ``b'\\x01'``).  With ``noise_addend ∈ [1, k-1]``,
    the noise token ``noise_c * k + noise_addend`` is never divisible by k,
    making it indistinguishable from a real token under GCD analysis.
    """
    digest = hmac.new(kb,
                      b'\x05' + nonce + ct_pos.to_bytes(5, 'big'),
                      hashlib.sha256).digest()
    return (int.from_bytes(digest[:4], 'big') % (key_element - 1)) + 1


def _derive_noise_p(kb: bytes, nonce: bytes) -> float:
    """Derive noise probability deterministically in [0.75, 0.99] from key and nonce.

    HMAC-SHA256 is keyed with the serialised encryption key and bound to the
    per-message nonce via domain separator ``b'\x02'``.  Because the nonce is
    fresh per message and the key is secret, the derived value is
    cryptographically unpredictable to any passive observer — it is never
    written to or stored in the ciphertext.
    """
    digest = hmac.new(kb, b'\x02' + nonce, hashlib.sha256).digest()
    t = int.from_bytes(digest[:8], 'big') / 2**64   # uniform in [0, 1)
    return 0.75 + t * (0.99 - 0.75)


def _derive_noise_threshold_v8(kb: bytes, nonce: bytes) -> int:
    """Return the v8 noise threshold theta(N), a 64-bit integer.

    The integer counterpart of :func:`_derive_noise_p`, and the normative form
    for the v8 block format (docs/napseq-eprint-v3.tex Section ``noiseprob``)::

        theta(N) = theta_min + floor(tau * (theta_max - theta_min) / 2**64)

    Division by ``2**64`` is exactly the high half of the 128-bit product, so
    the whole derivation is integer arithmetic with no rounding mode, no
    excess precision and no compiler licence to contract the expression --
    the three defects that made the IEEE-754 form of :func:`_derive_noise_p`
    only conditionally reproducible across languages and platforms.
    """
    digest = hmac.new(kb, b'\x02' + nonce, hashlib.sha256).digest()
    tau = int.from_bytes(digest[:8], 'big')
    return _THETA_MIN + ((tau * (_THETA_MAX - _THETA_MIN)) >> 64)


def _is_noise_pos_v8(kb: bytes, nonce: bytes, ct_pos: int,
                     theta: int) -> bool:
    """Integer-arithmetic counterpart of :func:`_is_noise_pos` for v8.

    Compares the full 64-bit derivation against theta(N) rather than a pair of
    doubles, so the noise schedule -- and hence the entire token stream -- is
    reproducible bit-for-bit by any conforming implementation.
    """
    digest = hmac.new(kb,
                      b'\x00' + nonce + ct_pos.to_bytes(5, 'big'),
                      hashlib.sha256).digest()
    return int.from_bytes(digest[:8], 'big') < theta


def _varint_keystream(kb: bytes, nonce: bytes, length: int) -> bytes:
    """Generate *length* keystream bytes for masking the block-mode token blob.

    Uses CTR-mode HMAC-SHA256: each 32-byte block is
    ``HMAC(key_bytes, b'\\x07' || nonce || uint32_be(block_index))``.
    Domain separator ``b'\\x07'`` is reserved exclusively for this purpose
    and does not overlap with any other derivation domain.

    Rationale (legacy v6 LEB128 blob): raw LEB128-encoded token values
    (c × k + addend, c ∈ [32, 127], k ≈ 10⁶) always occupy exactly 4 bytes.
    In 4-byte LEB128 encoding bytes 0-2 carry MSB=1 (continuation) and byte 3
    carries MSB=0 (terminal), producing a 3:1 MSB bias that fails every
    NIST SP 800-22 frequency test.

    Rationale (v7 fixed-width blob): the fixed-width big-endian encoding has
    no continuation-bit structure, but its high-order bytes are frequently
    zero (token magnitudes are well under 2**64), which is its own
    statistical bias. XORing the token blob with this keystream eliminates
    both biases without altering the wire layout
    (nonce ‖ masked_blob ‖ auth_tag), and — critically — the mask is applied
    to a blob whose *length* no longer depends on plaintext content (see
    CVF1 fix, ``docs/CAVEATS.md``), only on the padded codepoint count and
    the HMAC-derived noise schedule.
    """
    out = bytearray()
    block = 0
    while len(out) < length:
        digest = hmac.new(
            kb,
            b'\x07' + nonce + block.to_bytes(4, 'big'),
            hashlib.sha256,
        ).digest()
        out.extend(digest)
        block += 1
    return bytes(out[:length])


def _varint_keystream_blocks(kb: bytes, nonce: bytes) -> Generator[bytes, None, None]:
    """Yield successive 32-byte keystream blocks (domain 0x07) without a length cap.

    Used by the streaming API to apply the same LEB128-bias-eliminating XOR
    mask as the block API, one chunk at a time.
    """
    block = 0
    while True:
        yield hmac.new(
            kb,
            b'\x07' + nonce + block.to_bytes(4, 'big'),
            hashlib.sha256,
        ).digest()
        block += 1


def _compute_auth_tag(kb: bytes, aad: bytes, payload: bytes,
                      aad_len_width: int = 4) -> bytes:
    """Compute HMAC-SHA256 authentication tag for payload and optional AAD.

    Domain separator ``b'\x03'`` is used to isolate authentication from
    schedule/addend/noise derivation domains.  Layout (CVF2 fix): unified
    domain-first ``d || N || ctx`` shared by every domain in the schedule,
    with ``ctx = be(len(aad)) || aad || masked_blob``.  ``payload`` is
    ``nonce || masked_blob`` (see §5/§6 of SPEC.md); it is split here so the
    nonce occupies the fixed byte 1..16 offset used by every other domain.

    *aad_len_width* selects the width of the AAD length prefix: 8 bytes for
    v8 block mode (third-round audit finding CVF1 — the spec's TagIn is
    ``be8(|A|) || A || masked_blob``), 4 bytes for the legacy v7 and
    streaming-AE formats, which stay byte-compatible.
    """
    nonce, masked_blob = payload[:_NONCE_SIZE], payload[_NONCE_SIZE:]
    aad_len = len(aad).to_bytes(aad_len_width, 'big')
    msg = b'\x03' + nonce + aad_len + aad + masked_blob
    return hmac.new(kb, msg, hashlib.sha256).digest()


def _decode_v5_unauth(ciphertext: bytes, key: list[int]) -> str:
    """Legacy unauthenticated decode for v5 payloads (nonce || varint_blob)."""
    if len(ciphertext) < _NONCE_SIZE:
        raise ValueError(
            f"Ciphertext too short: {len(ciphertext)} bytes; "
            f"header requires at least {_NONCE_SIZE} bytes (nonce)."
        )
    nonce = ciphertext[:_NONCE_SIZE]
    token_blob = ciphertext[_NONCE_SIZE:]
    try:
        tokens = _b128_decode_tokens(token_blob)
    except IndexError as exc:
        raise ValueError(
            "Legacy v5 payload contains a truncated varint (continuation bit "
            "set on final byte); ciphertext is malformed."
        ) from exc
    return "".join(chr(c) for c in _decrypt(nonce, tokens, key))


# ─── Plaintext padding ───────────────────────────────────────────────────────

#: A padding profile is the map from plaintext codepoint count to padded block
#: size B (docs/napseq-eprint-v3.tex, Section "Padding Profiles").  It is the
#: only source of NAPQES's length-hiding property (Theorem ``lh-ind-cpa``); the
#: token expansion factor contributes none (Proposition ``expansion-neutral``).
#: Either the string ``"bucket"`` or a pair ``("coarse", g)`` / ``("frame", F)``.
PadProfile = Union[str, tuple[str, int]]

PAD_BUCKET: PadProfile = "bucket"

#: Exponent range of the reachable block sizes {2**4, ..., 2**16}.  Every
#: profile takes values in this same 13-element set, so the set of legal token
#: counts is profile-independent and a decryptor never needs to know which
#: profile the sender used.
_PAD_MIN_EXP = 4
_PAD_MAX_EXP = 16

#: The complete set of real-token counts R a well-formed v8 ciphertext can
#: carry.  Every padding profile pads to some B in {2**4, ..., 2**16} and the
#: padded buffer carries a 2-codepoint length prefix, so R = B + 2 always.
#: A decryptor that only checks divisibility by (MAX_NOISE_RUN + 1) would
#: accept an R outside this set and then run the token-extraction loop --
#: and, for a frame-profile ciphertext, allocate against an attacker-chosen
#: R (V3-CVF8).  Membership is checked explicitly, after tag verification.
_LEGAL_REAL_TOKEN_COUNTS = frozenset(
    (1 << e) + 2 for e in range(_PAD_MIN_EXP, _PAD_MAX_EXP + 1)
)


def _padding_bucket(n: int, profile: PadProfile = PAD_BUCKET) -> int:
    """Padded block size B for an *n*-codepoint message under *profile*.

    ``"bucket"`` (default) is the smallest power of two strictly above *n*,
    floored at 16, leaking at most log2(13) ~= 3.70 bits of length.
    ``("coarse", g)`` thins that ladder by a stride *g* dividing 12, leaving
    ``12 // g + 1`` reachable sizes.  ``("frame", F)`` pads every message to a
    single size *F*, leaking exactly zero bits, and requires ``n < F``.
    """
    e = max(_PAD_MIN_EXP, n.bit_length())
    if profile == PAD_BUCKET:
        return 1 << e
    if not (isinstance(profile, tuple) and len(profile) == 2):
        raise ValueError(
            f"Unknown padding profile {profile!r}; expected 'bucket', "
            "('coarse', g), or ('frame', F)."
        )
    kind, param = profile
    if kind == "coarse":
        span = _PAD_MAX_EXP - _PAD_MIN_EXP
        if param < 1 or span % param:
            raise ValueError(
                f"coarse stride g={param} must divide {span} "
                f"(one of {[g for g in range(1, span + 1) if span % g == 0]})."
            )
        steps = -(-(e - _PAD_MIN_EXP) // param)          # ceil division
        return 1 << (_PAD_MIN_EXP + param * steps)
    if kind == "frame":
        # Guard before the bit_length()/shift arithmetic: F=0 would give
        # exp=-1 and `1 << -1` raises "negative shift count", which tells the
        # caller nothing about the actual constraint.
        if not isinstance(param, int) or isinstance(param, bool) or param < 1:
            raise ValueError(
                f"frame size F={param!r} must be a power of two in "
                f"[{1 << _PAD_MIN_EXP}, {1 << _PAD_MAX_EXP}]."
            )
        exp = param.bit_length() - 1
        if 1 << exp != param or not _PAD_MIN_EXP <= exp <= _PAD_MAX_EXP:
            raise ValueError(
                f"frame size F={param} must be a power of two in "
                f"[{1 << _PAD_MIN_EXP}, {1 << _PAD_MAX_EXP}]."
            )
        if n >= param:
            raise ValueError(
                f"frame({param}) profile admits messages of at most "
                f"{param - 1} codepoints; got {n}. Use a larger frame."
            )
        return param
    raise ValueError(
        f"Unknown padding profile {profile!r}; expected 'bucket', "
        "('coarse', g), or ('frame', F)."
    )


def _pad_message(msg: list[int], kb: bytes, nonce: bytes,
                 pad_profile: PadProfile = PAD_BUCKET) -> list[int]:
    """Pad *msg* to the block size selected by *pad_profile*.

    Layout: [len_hi, len_lo] + original_msg + hmac_padding
    where block_size = :func:`_padding_bucket` of len(msg).
    Total output length: 2 + block_size.

    The 2-codepoint length prefix stores the original message length as a
    big-endian 16-bit integer (max 65535 codepoints).  Padding codepoints
    are HMAC-derived from (key, nonce, pad_index) using domain separator
    ``b'\x06'``, placing each in printable ASCII [32, 126].  HMAC-derived
    padding makes the scheme fully deterministic given (key, nonce, plaintext),
    which enables cross-implementation Known-Answer Tests (KATs).
    """
    n = len(msg)
    if n > MAX_PLAINTEXT_CODEPOINTS:
        raise ValueError(
            f"Message too long for 2-byte length prefix "
            f"(got {n} codepoints, max {MAX_PLAINTEXT_CODEPOINTS}). "
            f"See napqes.MAX_PLAINTEXT_CODEPOINTS and docs/CAVEATS.md."
        )
    block_size = _padding_bucket(n, pad_profile)
    pad_len    = block_size - n
    padding: list[int] = []
    for i in range(pad_len):
        d = hmac.new(kb, b'\x06' + nonce + i.to_bytes(4, 'big'), hashlib.sha256).digest()
        padding.append((int.from_bytes(d[:4], 'big') % 95) + 32)  # [32, 126]
    return [n >> 8, n & 0xFF] + msg + padding


def _unpad_message(padded: list[int]) -> list[int]:
    """Recover the original message from a padded codepoint list.

    Reads the 2-codepoint big-endian length prefix written by ``_pad_message``
    and slices the original content from the padded buffer.
    """
    if len(padded) < 2:
        raise ValueError("Padded message too short to contain length prefix.")
    n = (padded[0] << 8) | padded[1]
    if 2 + n > len(padded):
        raise ValueError(
            f"Length prefix ({n}) exceeds available data ({len(padded) - 2} bytes)."
        )
    return padded[2 : 2 + n]


# ─── Core encrypt / decrypt ──────────────────────────────────────────────────

def encrypt(message: list[int], key: list[int]) -> tuple[bytes, list[int]]:
    """Encrypt *message* (list of integer codepoints).

    Returns ``(nonce, tokens)``; ``encrypt_str`` / ``encrypt_bytes`` embed
    them in a single self-contained ciphertext.  The noise probability is
    derived deterministically from the key and nonce via HMAC-SHA256 and is
    never transmitted — a passive observer cannot recover it without the key.

    Security enhancements:
      • Noise probability is HMAC-derived from key+nonce per call, hidden
        from ciphertext observers and unpredictable without the secret key.
      • Plaintext is transparently padded to a power-of-two block size,
        reducing length leakage to revealing only the power-of-two bucket.
      • Noise positions and real-token addends are HMAC-derived, so the
        key cannot be recovered via divisibility, frequency, or ratio attacks.
    """
    _validate_key(key)
    nonce    = secrets.token_bytes(16)
    kb       = _key_bytes(key)
    noise_probability = _derive_noise_p(kb, nonce)
    padded   = _pad_message(message, kb, nonce)
    K        = len(key)

    cypher:   list[int] = []
    real_idx: int = 0
    ct_pos:   int = 0

    for c in padded:
        while True:
            if _is_noise_pos(kb, nonce, ct_pos, noise_probability):
                # Noise tokens use noise_c * k + noise_addend — same formula
                # as real tokens.  noise_c ∈ [32,127] and noise_addend ∈ [1,k−1]
                # are HMAC-derived (domains 0x04, 0x05), so the token is
                # never an exact multiple of k and can never equal
                # known_cp * k for any integer known_cp, defeating the
                # known-plaintext divisibility attack on noise tokens.
                k          = key[real_idx % K]
                noise_c    = _derive_noise_char(kb, nonce, ct_pos)
                noise_add  = _derive_noise_token_addend(kb, nonce, ct_pos, k)
                cypher.append(noise_c * k + noise_add)
                ct_pos += 1
            else:
                k      = key[real_idx % K]
                addend = _derive_addend(kb, nonce, real_idx, k)
                cypher.append(c * k + addend)
                ct_pos  += 1
                real_idx += 1
                break

    return nonce, cypher


def _decrypt_with_noise_p(nonce: bytes, cypher: list[int], key: list[int],
                          noise_probability: float) -> list[int]:
    """Internal decrypt with an explicit noise_probability.

    Used by the legacy v2/v3 backward-compat path in ``decrypt_str``, which
    reads the stored noise_p from the old colon-delimited ciphertext format.
    New code should always use ``_decrypt`` or the authenticated ``decrypt_bytes`` API.
    """
    _validate_key(key)
    kb       = _key_bytes(key)
    K        = len(key)
    padded:  list[int] = []
    real_idx: int = 0

    for ct_pos, token in enumerate(cypher):
        if not _is_noise_pos(kb, nonce, ct_pos, noise_probability):
            k      = key[real_idx % K]
            addend = _derive_addend(kb, nonce, real_idx, k)
            padded.append((token - addend) // k)
            real_idx += 1

    return _unpad_message(padded)


def _decrypt(nonce: bytes, cypher: list[int], key: list[int]) -> list[int]:
    """Decrypt tokens produced by ``encrypt`` — internal, unauthenticated.

    *noise_probability* is derived from *key* and *nonce* via HMAC-SHA256,
    exactly as during encryption — it is never transmitted or required as a
    parameter.  A wrong key or nonce yields incorrect output without raising
    an error.  Padding added by ``encrypt`` is stripped automatically.

    This function performs no authenticity check.  External callers should use
    ``decrypt_bytes`` or ``decrypt_str`` which verify the HMAC tag before
    returning plaintext.
    """
    _validate_nonce(nonce)
    _validate_cypher(cypher)
    _validate_key(key)
    kb = _key_bytes(key)
    noise_probability = _derive_noise_p(kb, nonce)
    return _decrypt_with_noise_p(nonce, cypher, key, noise_probability)


# ─── Base-128 (varint) token encoding ────────────────────────────────────────
# Encodes each integer token as a Protocol-Buffers-style unsigned varint:
# 7 bits are stored per byte; the MSB is 1 if more bytes follow, 0 for the
# final byte of each value.  All encoded bytes are concatenated.

def _b128_encode_tokens(tokens: list[int]) -> bytes:
    """Encode a list of non-negative integers as concatenated base-128 varints."""
    out = bytearray()
    for n in tokens:
        while n > 0x7F:
            out.append((n & 0x7F) | 0x80)
            n >>= 7
        out.append(n & 0x7F)
    return bytes(out)


def _b128_encode_token(n: int) -> bytes:
    """Encode a single non-negative integer as a base-128 varint."""
    out = bytearray()
    while n > 0x7F:
        out.append((n & 0x7F) | 0x80)
        n >>= 7
    out.append(n & 0x7F)
    return bytes(out)


def _b128_decode_tokens(data: bytes) -> list[int]:
    """Decode a concatenated base-128 varint blob back to a list of integers.

    Retained only to decode legacy v6 ciphertexts (``legacy_v6_varint=True``).
    New ciphertexts are produced with :func:`_fixed_encode_tokens` — see CVF1.
    """
    tokens: list[int] = []
    i = 0
    while i < len(data):
        value = 0
        shift = 0
        while True:
            b = data[i]; i += 1
            value |= (b & 0x7F) << shift
            if not (b & 0x80):
                break
            shift += 7
        tokens.append(value)
    return tokens


# ─── Fixed-width token encoding (v7 — CVF1 fix) ──────────────────────────────
# Audit finding CVF1 (docs/CAVEATS.md): the legacy v6 LEB128 varint encoding
# gives each token a byte-length that grows with its magnitude, and token
# magnitude is c * k + addend where c is the plaintext codepoint. Two
# plaintexts with the same padded codepoint count therefore produced
# ciphertexts of different byte-length depending on codepoint *values*,
# breaking the IND-CPA hiding argument (equal padded length was assumed to
# imply equal blob byte-length; it did not).
#
# The fix: encode every token in a constant-width big-endian field. The
# serialised blob length is then exactly (token_count * _TOKEN_WIDTH) bytes,
# and token_count is a function of the padded codepoint count and the
# HMAC-derived noise schedule (both of which depend only on (key, nonce,
# padded length) — never on the plaintext codepoint values). Blob length is
# therefore content-independent, closing the CVF1 side channel.

#: Width in bytes of each fixed-width token field. Sized to comfortably hold
#: the largest possible token: codepoint <= 0x10FFFF (~2**21) times a key
#: element < 2**40 (the 5-byte serialised width used by _key_bytes), plus an
#: addend < key element, bounds the token well under 2**64 - 1.
_TOKEN_WIDTH = 8
_TOKEN_MAX = (1 << (8 * _TOKEN_WIDTH)) - 1


def _fixed_encode_tokens(tokens: list[int]) -> bytes:
    """Encode a list of non-negative integers as concatenated fixed-width fields.

    Each token occupies exactly ``_TOKEN_WIDTH`` big-endian bytes regardless
    of magnitude, so the output length is ``len(tokens) * _TOKEN_WIDTH`` —
    independent of the token values.  This is the v7 wire encoding that
    fixes CVF1 (see module docstring and ``docs/CAVEATS.md``).
    """
    out = bytearray()
    for n in tokens:
        if n > _TOKEN_MAX:
            raise ValueError(
                f"Token value {n} exceeds the {_TOKEN_WIDTH}-byte fixed-width "
                f"field (max {_TOKEN_MAX}); cannot serialise without truncation."
            )
        out += n.to_bytes(_TOKEN_WIDTH, 'big')
    return bytes(out)


def _fixed_decode_tokens(data: bytes) -> list[int]:
    """Decode a concatenated fixed-width token blob back to a list of integers."""
    if len(data) % _TOKEN_WIDTH != 0:
        raise ValueError(
            f"Fixed-width token blob length ({len(data)}) is not a multiple "
            f"of {_TOKEN_WIDTH} bytes; ciphertext is malformed, or was "
            "produced by the legacy v6 LEB128 encoding (pass "
            "legacy_v6_varint=True to decode it)."
        )
    return [
        int.from_bytes(data[i:i + _TOKEN_WIDTH], 'big')
        for i in range(0, len(data), _TOKEN_WIDTH)
    ]


# ─── Binary transport ───────────────────────────────────────────────────────────────
# Ciphertext binary format v7 (authenticated) — CVF1 fix:
#   nonce (16 bytes) || masked_blob (token_count * 8 bytes) || auth_tag (32 bytes)
# where auth_tag = HMAC-SHA256(key_bytes, b'\x03' || len(aad) || aad || payload)
# and payload = nonce || masked_blob
#       masked_blob = token_blob XOR _varint_keystream(key_bytes, nonce, len(token_blob))
#       token_blob  = _fixed_encode_tokens(tokens)   # 8 bytes/token, big-endian
#
# masked_blob's length is (token_count * 8), and token_count depends only on
# the padded codepoint count and the HMAC-derived noise schedule — never on
# plaintext codepoint values. This closes the CVF1 content-dependent length
# leak present in the retired v6 LEB128 encoding (still readable via the
# explicit ``legacy_v6_varint=True`` opt-in on ``decrypt_bytes``/``decrypt_str``).
#
# The scheme provides confidentiality + integrity/authenticity for v7 data.
# Legacy unauthenticated v5 blobs can still be decoded with explicit opt-in.
#
# The string wrappers base64-encode (RFC 4648) the full binary blob for
# safe embedding in text protocols (JSON, HTTP headers, etc.).

def encrypt_bytes(message: str, key: list[int], aad: bytes = b"") -> bytes:
    """Encrypt *message* and return a compact binary ciphertext (v7 format).

    Wire layout:  nonce (16 B) || masked_blob || auth_tag (32 B).
    masked_blob = token_blob XOR _varint_keystream(key_bytes, nonce, len(token_blob)),
    where token_blob is the fixed-width (8 bytes/token, big-endian) encoding
    produced by ``_fixed_encode_tokens``. Every token occupies the same
    number of bytes regardless of magnitude, so masked_blob's length depends
    only on the *number* of tokens — a function of the padded codepoint
    count and the HMAC-derived noise schedule — and never on plaintext
    codepoint values. This is the fix for audit finding CVF1: the retired v6
    LEB128 encoding's per-token byte-length grew with codepoint magnitude,
    leaking plaintext content through ciphertext length even between
    messages of equal padded length.
    noise_probability is derived from key+nonce via HMAC and never stored.
    The auth tag is HMAC-SHA256 over the payload (nonce || masked_blob) plus
    optional AAD, providing ciphertext integrity and authenticity.
    No encoding overhead; suitable for binary sockets, files, or any
    binary-safe channel.

    **Key ordering is a security parameter.** ``[k0, k1, …]`` and
    ``[k1, k0, …]`` are distinct keys that produce non-interoperable
    ciphertexts. Callers must preserve element order when storing or
    transmitting key material.
    """
    nonce, tokens = encrypt([ord(c) for c in message], key)
    kb = _key_bytes(key)
    token_blob = _fixed_encode_tokens(tokens)
    ks = _varint_keystream(kb, nonce, len(token_blob))
    masked_blob = bytes(a ^ b for a, b in zip(token_blob, ks))
    payload = nonce + masked_blob
    tag = _compute_auth_tag(kb, aad, payload)
    return payload + tag


def decrypt_bytes(ciphertext: bytes, key: list[int], aad: bytes = b"",
                  allow_legacy_unauthenticated: bool = False,
                  legacy_v6_varint: bool = False) -> str:
    """Decrypt a binary ciphertext produced by ``encrypt_bytes``.

    Accepts v7 format (default): nonce (16 B) || masked_blob || auth_tag (32 B),
    where masked_blob XOR-unmasks to fixed-width (8-byte) tokens — see CVF1
    and the module docstring.  noise_probability is re-derived from key+nonce
    via HMAC — not read from the ciphertext.

    Pass ``legacy_v6_varint=True`` to decode ciphertexts produced before the
    CVF1 fix, whose masked_blob unmasks to variable-length LEB128 tokens
    instead. Such ciphertexts remain fully authenticated; the flag only
    selects the token *deserialisation* format and does not weaken integrity
    checking.

    If ``allow_legacy_unauthenticated`` is True, this function will also
    decode old v5 payloads (nonce || varint_blob) without integrity checks.
    """
    _validate_key(key)
    if len(ciphertext) >= (_NONCE_SIZE + _TAG_SIZE):
        kb = _key_bytes(key)
        payload = ciphertext[:-_TAG_SIZE]
        recv_tag = ciphertext[-_TAG_SIZE:]
        calc_tag = _compute_auth_tag(kb, aad, payload)
        if hmac.compare_digest(recv_tag, calc_tag):
            nonce = payload[:_NONCE_SIZE]
            masked_blob = payload[_NONCE_SIZE:]
            ks = _varint_keystream(kb, nonce, len(masked_blob))
            token_blob = bytes(a ^ b for a, b in zip(masked_blob, ks))
            if legacy_v6_varint:
                tokens = _b128_decode_tokens(token_blob)
            else:
                tokens = _fixed_decode_tokens(token_blob)
            return "".join(chr(c) for c in _decrypt(nonce, tokens, key))
        if not allow_legacy_unauthenticated:
            raise ValueError("Authentication failed: invalid HMAC tag.")
    if allow_legacy_unauthenticated:
        return _decode_v5_unauth(ciphertext, key)
    raise ValueError(
        "Ciphertext is not a valid authenticated v7 payload. "
        "To decode legacy v6 payloads (pre-CVF1 fix), set legacy_v6_varint=True. "
        "To decode legacy v5 unauthenticated payloads, set "
        "allow_legacy_unauthenticated=True."
    )


# ─── V8: misuse-resistant synthetic-nonce construction (CVF3/CVF8/CVF13 fix) ─
#
# v7's nonce is a fresh 128-bit CSPRNG draw per call. Every internal value
# (noise schedule, addends, keystream, tag) is a deterministic function of
# (key_bytes(key), nonce) alone, so a *reused* nonce reproduces an identical
# keystream/schedule; combined with the exact affine token map c*k+a, this
# lets an attacker recover the key exactly from two known plaintexts under
# one reused nonce (docs/napseq-eprint-preprint.tex, Table "comparison"
# footnote; docs/CAVEATS.md CVF3). A CSPRNG nonce only makes *accidental*
# reuse improbable — it does nothing against DRBG failure, process
# restart/replay, or VM/container snapshot-and-restore.
#
# v8 closes this by construction (SIV-style synthetic nonce, RFC 5297 /
# AES-GCM-SIV): the nonce is *derived*, not drawn, as a keyed HMAC of the
# (aad, message) being encrypted, under an **independently**-sampled 256-bit
# subkey `sk` that is never a function of the prime-tuple key. See
# docs/napseq-eprint-preprint.tex §"V8 Key Schedule and Synthetic Nonce"
# (Definitions keygen-v8, synthnonce; Lemmas v8-cvf3/v8-cvf8/v8-cvf13).
#
# This implementation additionally derives a per-wire-format subkey
# (domain 0x0B, `sk_fmt = HMAC(sk, 0x0B || format_id)`) and uses `sk_fmt` in
# place of `sk` for every subsequent domain derivation (0x00-0x0A). This is
# an extension beyond the current paper text (which uses `sk` directly for
# domain 0x0A): it ensures a ciphertext/tag produced for one wire format
# (e.g. block mode) can never verify under another format's effective key
# (e.g. streaming-AE), even though both share the same (primes, sk) key
# material — closing a format-confusion hazard that a shared `sk` alone
# does not. The paper will be updated to document domain 0x0B explicitly
# (tracked follow-up).
#
# v8 is *additive*: v7 (`encrypt_bytes`/`decrypt_bytes`) is unchanged and
# remains available. v8 and v7 ciphertexts are not interoperable (different
# keying and nonce derivation) — callers must agree out-of-band on which
# schedule a given key/ciphertext pair uses, per
# docs/napseq-eprint-preprint.tex §"Format Applicability".

#: Width in bytes of the independently-sampled v8 HMAC subkey ``sk``.
SK_SIZE = 32

#: Hard cap on consecutive noise tokens emitted before a real token, applied
#: only by the v8 token-emission loop (never by v7, to keep old v7
#: ciphertexts decodable exactly as originally produced). Without a cap, the
#: noise-probability range [0.75, 0.99] implies a *worst-case* expansion of
#: up to ~100 tokens per real codepoint (mean 1/(1-p) at p=0.99), far above
#: the "4-20x" figure documented for ciphertext expansion. Capping at 19
#: consecutive noise tokens bounds the worst case to exactly
#: (MAX_NOISE_RUN + 1) = 20 tokens per real codepoint, matching the
#: documented "<=20x" bound exactly. The cap is a deterministic, public
#: counter comparison (not a secret-dependent decision), so it introduces no
#: new side channel and both encryption and decryption apply it identically.
#:
#: As of the V2-CVF2 fix (2026-07-21, docs/CAVEATS.md), this cap also fixes
#: the *total* per-real-token budget used to pad every v8 ciphertext up to a
#: deterministic per-bucket ceiling of ``real_token_count * (MAX_NOISE_RUN +
#: 1)`` tokens (see :func:`_encrypt_v8_core` / :func:`_decrypt_v8_core`):
#: v8 ciphertext length is therefore now a pure function of the padding
#: bucket alone, never of the message-derived synthetic nonce's noise
#: realisation, at the cost of always paying the worst-case ~20x expansion
#: (previously the average case was ~13.4x). v7 is unaffected — it keeps its
#: original average-case-length, uncapped-ceiling behaviour.
MAX_NOISE_RUN = 19

#: Domain 0x0B format-subkey identifiers. Passed to `_derive_format_subkey`
#: to bind every v8 derivation to the specific wire format in use.
FORMAT_BLOCK_V8 = 0x01
FORMAT_STREAM_AE_V8 = 0x02


def generate_v8_key(count: int = 10,
                    min_val: int = MIN_KEY_PRIME,
                    max_val: int = MAX_KEY_PRIME) -> tuple[list[int], bytes]:
    """Generate v8 key material: ``(primes, sk)``.

    *primes* is generated exactly as by :func:`generate_prime_numbers` and is
    used only by the public, un-keyed arithmetic token map ``c * k + a``
    (Section "Token Construction"). *sk* is an **independently**-sampled
    256-bit CSPRNG subkey that keys every HMAC domain derivation in place of
    ``key_bytes(primes)``. No function relates *sk* to *primes*; both are
    secret key material that MUST be generated, stored, and transmitted
    together (docs/napseq-eprint-preprint.tex, Definition ``keygen-v8``).
    """
    primes = generate_prime_numbers(count, min_val, max_val)
    sk = secrets.token_bytes(SK_SIZE)
    return primes, sk


def zeroize_key(key: list[int]) -> None:
    """Best-effort in-place zeroization of a prime-tuple key list.

    Python ``int`` values are immutable, so this cannot guarantee the
    original prime values are scrubbed from every place they were ever
    referenced in memory (unlike, e.g., Rust's ``zeroize_key``) — it
    overwrites *this list's* contents so that a leaked reference to *key*
    read after this call sees zeros instead of key elements.
    """
    for i in range(len(key)):
        key[i] = 0


def zeroize_sk(sk: bytearray) -> None:
    """Zero the bytes of a v8 HMAC subkey in place.

    *sk* must be a mutable ``bytearray`` (not immutable ``bytes``) for the
    zeroization to take effect; :func:`generate_v8_key` returns ``bytes`` for
    API consistency with ``aad``, so callers who need zeroization should
    convert with ``bytearray(sk)`` and pass that mutable copy around instead.
    """
    for i in range(len(sk)):
        sk[i] = 0


def _derive_format_subkey(sk: bytes, format_id: int) -> bytes:
    """Domain ``0x0B``: derive a format-specific HMAC subkey from *sk*.

    Prevents a ciphertext/tag produced under one v8 wire format (block vs.
    streaming-AE) from ever verifying under another format's effective key,
    even though both share the same ``(primes, sk)`` key material.
    """
    return hmac.new(sk, b'\x0b' + bytes([format_id]), hashlib.sha256).digest()


def _synthetic_nonce(sk_fmt: bytes, aad: bytes, message: bytes) -> bytes:
    """Domain ``0x0A``: SIV-style synthetic nonce, deterministic in
    ``(sk_fmt, aad, message)``.

    ``N = HMAC(sk_fmt, 0x0A || be8(len(aad)) || aad || message)[0:16]``.
    Re-encrypting an identical ``(aad, message)`` reproduces the identical
    nonce (and hence identical ciphertext) — the standard, disclosed MRAE
    trade-off (cf. AES-GCM-SIV) — while distinct messages get distinct
    nonces with overwhelming probability (a PRF/birthday event, not a
    CSPRNG-luck event), closing the v7 nonce-reuse key-recovery hazard by
    construction.
    """
    aad_len = len(aad).to_bytes(_AAD_LEN_WIDTH_V8, 'big')
    digest = hmac.new(sk_fmt, b'\x0a' + aad_len + aad + message, hashlib.sha256).digest()
    return digest[:_NONCE_SIZE]


def _encrypt_v8_core(message: list[int], key: list[int], key_material: bytes,
                     nonce: bytes,
                     pad_profile: PadProfile = PAD_BUCKET) -> list[int]:
    """v8 token-emission loop.

    Identical to the v7 loop in :func:`encrypt` except every HMAC domain
    derivation is keyed by *key_material* (the v8 format subkey) instead of
    ``key_bytes(key)``, and a hard cap of :data:`MAX_NOISE_RUN` consecutive
    noise tokens bounds worst-case ciphertext expansion. *key* (the prime
    tuple) is still used directly, un-keyed, for the arithmetic token map
    ``c * k + a`` — exactly as in v7.

    V2-CVF2 fix: after the natural real/noise sequence is emitted, the
    output is padded with additional, structurally identical filler tokens
    up to a fixed ceiling of ``len(padded) * (MAX_NOISE_RUN + 1)`` tokens.
    Because the synthetic nonce is a function of the message
    (Definition ``synthnonce``), the *natural* token count would otherwise
    vary with the message even for a fixed padding bucket, letting an
    observer who collects several ciphertexts of one message under varying
    AAD average out the noise and reliably recover the padding bucket
    (docs/CAVEATS.md, V2-CVF2). Padding to a bucket-only ceiling removes
    that variance: v8 ciphertext length is now a deterministic function of
    ``len(padded)`` (the padding bucket) alone, exactly like v7's
    Lemma~tar guarantee, at the cost of always paying the worst-case
    expansion instead of the ~13.4x average case.
    """
    noise_theta = _derive_noise_threshold_v8(key_material, nonce)
    padded = _pad_message(message, key_material, nonce, pad_profile)
    K = len(key)

    cypher: list[int] = []
    real_idx = 0
    ct_pos = 0

    for c in padded:
        noise_run = 0
        while (noise_run < MAX_NOISE_RUN
               and _is_noise_pos_v8(key_material, nonce, ct_pos, noise_theta)):
            k = key[real_idx % K]
            noise_c = _derive_noise_char(key_material, nonce, ct_pos)
            noise_add = _derive_noise_token_addend(key_material, nonce, ct_pos, k)
            cypher.append(noise_c * k + noise_add)
            ct_pos += 1
            noise_run += 1
        k = key[real_idx % K]
        addend = _derive_addend(key_material, nonce, real_idx, k)
        cypher.append(c * k + addend)
        ct_pos += 1
        real_idx += 1

    # V2-CVF2 fix: pad up to the fixed, bucket-only ceiling so |C| never
    # depends on the message-derived nonce's noise realisation.
    ceiling = len(padded) * (MAX_NOISE_RUN + 1)
    while len(cypher) < ceiling:
        k = key[real_idx % K]
        noise_c = _derive_noise_char(key_material, nonce, ct_pos)
        noise_add = _derive_noise_token_addend(key_material, nonce, ct_pos, k)
        cypher.append(noise_c * k + noise_add)
        ct_pos += 1

    return cypher


def _decrypt_v8_core(nonce: bytes, cypher: list[int], key: list[int],
                     key_material: bytes) -> list[int]:
    """Inverse of :func:`_encrypt_v8_core`.

    Applies the identical :data:`MAX_NOISE_RUN`-capped schedule derivation so
    encryption and decryption stay in lock-step. Raises ``ValueError`` (never
    ``IndexError``) if the token stream is truncated mid noise-run.

    V2-CVF2 fix: the real-token count ``R`` is no longer discovered by
    consuming tokens until the blob is exhausted. Instead, because
    :func:`_encrypt_v8_core` always pads the token count up to exactly
    ``R * (MAX_NOISE_RUN + 1)``, ``R`` is recovered directly from the total
    token count up front; decoding stops as soon as ``R`` real tokens have
    been extracted, and any trailing filler tokens are ignored rather than
    being fed through the noise/real decision loop.
    """
    noise_theta = _derive_noise_threshold_v8(key_material, nonce)
    K = len(key)
    padded: list[int] = []
    real_idx = 0
    ct_pos = 0
    n = len(cypher)
    ceiling_unit = MAX_NOISE_RUN + 1

    if n % ceiling_unit != 0:
        raise ValueError(
            "Malformed v8 ciphertext: token count is not a multiple of the "
            f"padding ceiling ({ceiling_unit}); expected exactly "
            "real_token_count * (MAX_NOISE_RUN + 1) tokens."
        )
    real_count = n // ceiling_unit

    # V3-CVF8: R must be one of the 13 counts a padding profile can produce,
    # R = B + 2 for B in {2**4, ..., 2**16}.  Reached only after the tag has
    # verified (see decrypt_bytes_v8), so this rejects a malformed ciphertext
    # forged by a holder of sk, never an unauthenticated attacker input.
    if real_count not in _LEGAL_REAL_TOKEN_COUNTS:
        raise ValueError(
            f"Malformed v8 ciphertext: real-token count {real_count} is not "
            f"B + 2 for any reachable padded block size B in "
            f"[{1 << _PAD_MIN_EXP}, {1 << _PAD_MAX_EXP}]; legal counts are "
            f"{sorted(_LEGAL_REAL_TOKEN_COUNTS)}."
        )

    while real_idx < real_count:
        noise_run = 0
        while (noise_run < MAX_NOISE_RUN
               and ct_pos < n
               and _is_noise_pos_v8(key_material, nonce, ct_pos, noise_theta)):
            ct_pos += 1
            noise_run += 1
        if ct_pos >= n:
            raise ValueError(
                "Truncated v8 ciphertext: token stream ended mid noise-run "
                "before the expected real token."
            )
        k = key[real_idx % K]
        addend = _derive_addend(key_material, nonce, real_idx, k)
        token = cypher[ct_pos]
        # A genuine real token is exactly c * k + addend with addend in
        # [1, k - 1], so the subtraction never underflows and the quotient is
        # exact. Checking both rather than relying on floor division keeps the
        # three ports in lock-step: an unchecked subtraction wraps in Rust
        # release builds and in C, and panics in Rust debug builds.
        if token < addend or (token - addend) % k != 0:
            raise ValueError(
                f"Malformed v8 ciphertext: token at position {ct_pos} is not "
                f"of the form codepoint * k + addend for key element {k}."
            )
        cp = (token - addend) // k
        if cp > 0x10FFFF or 0xD800 <= cp <= 0xDFFF:
            raise ValueError(
                f"Malformed v8 ciphertext: recovered value {cp} at position "
                f"{ct_pos} is not a Unicode scalar value."
            )
        padded.append(cp)
        ct_pos += 1
        real_idx += 1

    return _unpad_message(padded)


def _validate_message_domain(message: str) -> None:
    """Reject strings outside the message space M of the security analysis.

    M is the set of finite sequences of Unicode *scalar values* -- codepoints
    in [U+0000, U+10FFFF] excluding the surrogate range [U+D800, U+DFFF]
    (docs/napseq-eprint-v3.tex, Section "The AEAD Triple").  Surrogates are
    excluded because the synthetic-nonce derivation hashes the UTF-8 encoding
    of the message and UTF-8 is undefined on unpaired surrogates.  Without
    this check Python raises a UnicodeEncodeError from deep inside the nonce
    derivation, which is both opaque and inconsistent with the Rust port,
    whose ``&str`` type excludes surrogates by construction.
    """
    for i, ch in enumerate(message):
        if 0xD800 <= ord(ch) <= 0xDFFF:
            raise ValueError(
                f"message contains a surrogate codepoint U+{ord(ch):04X} at "
                f"position {i}; the message space excludes U+D800..U+DFFF "
                f"(docs/napseq-eprint-v3.tex, message space M)."
            )


def encrypt_bytes_v8(message: str, primes: list[int], sk: bytes,
                     aad: bytes = b"",
                     pad_profile: PadProfile = PAD_BUCKET) -> bytes:
    """Misuse-resistant v8 block-mode encryption (synthetic nonce, independent
    subkey).

    Closes the catastrophic v7 nonce-reuse key-recovery hazard (CVF3), the
    non-standard key-entropy PRF assumption (CVF8), and the reduction-
    simulation gap (CVF13) — see docs/napseq-eprint-preprint.tex §"V8 Key
    Schedule", Lemmas v8-cvf3/v8-cvf8/v8-cvf13.

    *primes* is a prime-tuple key exactly as accepted by ``encrypt_bytes``
    (used only for the public, un-keyed arithmetic token map). *sk* is an
    **independently**-sampled 256-bit subkey (see :func:`generate_v8_key`)
    that keys every internal HMAC derivation, including the nonce itself.

    Unlike ``encrypt_bytes`` (v7), the nonce is *not* drawn from a CSPRNG: it
    is derived deterministically from ``(sk, aad, message)`` (domain 0x0A),
    a SIV-style synthetic IV. Encrypting the same ``(sk, aad, message)``
    twice yields byte-identical ciphertext (the disclosed MRAE trade-off);
    distinct messages get distinct nonces with overwhelming probability.

    v8 ciphertexts are **not interoperable** with v7 ciphertexts; callers
    must agree out-of-band on which schedule a given key/ciphertext pair
    uses (see docs/napseq-eprint-preprint.tex §"Format Applicability").

    *pad_profile* selects the padding profile (docs/napseq-eprint-v3.tex,
    Section "Padding Profiles"), which is what governs how much plaintext
    length the ciphertext size reveals: ``"bucket"`` (default) leaks at most
    ~3.70 bits, ``("frame", F)`` leaks exactly zero.  It is a sender-side
    deployment parameter agreed out of band and is never transmitted;
    decryption is profile-agnostic and needs no matching argument.
    """
    _validate_key(primes)
    if len(sk) != SK_SIZE:
        raise ValueError(f"sk must be exactly {SK_SIZE} bytes, got {len(sk)}.")
    _validate_message_domain(message)
    sk_fmt = _derive_format_subkey(sk, FORMAT_BLOCK_V8)
    message_bytes = message.encode("utf-8")
    nonce = _synthetic_nonce(sk_fmt, aad, message_bytes)
    codepoints = [ord(c) for c in message]
    tokens = _encrypt_v8_core(codepoints, primes, sk_fmt, nonce, pad_profile)
    token_blob = _fixed_encode_tokens(tokens)
    ks = _varint_keystream(sk_fmt, nonce, len(token_blob))
    masked_blob = bytes(a ^ b for a, b in zip(token_blob, ks))
    payload = nonce + masked_blob
    tag = _compute_auth_tag(sk_fmt, aad, payload, _AAD_LEN_WIDTH_V8)
    return payload + tag


def decrypt_bytes_v8(ciphertext: bytes, primes: list[int], sk: bytes,
                     aad: bytes = b"") -> str:
    """Decrypt a v8 ciphertext produced by :func:`encrypt_bytes_v8`.

    Raises ``ValueError`` on tag mismatch, undersized ciphertext, or a
    malformed token blob — mirroring ``decrypt_bytes``'s error model.
    """
    _validate_key(primes)
    if len(sk) != SK_SIZE:
        raise ValueError(f"sk must be exactly {SK_SIZE} bytes, got {len(sk)}.")
    if len(ciphertext) < (_NONCE_SIZE + _TAG_SIZE):
        raise ValueError(
            f"Ciphertext too short: {len(ciphertext)} bytes; header+tag "
            f"require at least {_NONCE_SIZE + _TAG_SIZE} bytes."
        )
    sk_fmt = _derive_format_subkey(sk, FORMAT_BLOCK_V8)
    payload = ciphertext[:-_TAG_SIZE]
    recv_tag = ciphertext[-_TAG_SIZE:]
    calc_tag = _compute_auth_tag(sk_fmt, aad, payload, _AAD_LEN_WIDTH_V8)
    if not hmac.compare_digest(recv_tag, calc_tag):
        raise ValueError("Authentication failed: invalid HMAC tag (v8).")
    nonce = payload[:_NONCE_SIZE]
    masked_blob = payload[_NONCE_SIZE:]
    ks = _varint_keystream(sk_fmt, nonce, len(masked_blob))
    token_blob = bytes(a ^ b for a, b in zip(masked_blob, ks))
    tokens = _fixed_decode_tokens(token_blob)
    codepoints = _decrypt_v8_core(nonce, tokens, primes, sk_fmt)
    return "".join(chr(c) for c in codepoints)


def encrypt_str_v8(message: str, primes: list[int], sk: bytes,
                   aad: bytes = b"",
                   pad_profile: PadProfile = PAD_BUCKET) -> str:
    """Base64-wrapped wrapper around :func:`encrypt_bytes_v8`."""
    return base64.b64encode(
        encrypt_bytes_v8(message, primes, sk, aad, pad_profile)
    ).decode("ascii")


def decrypt_str_v8(cypher: str, primes: list[int], sk: bytes,
                   aad: bytes = b"") -> str:
    """Base64-wrapped wrapper around :func:`decrypt_bytes_v8`."""
    return decrypt_bytes_v8(base64.b64decode(cypher), primes, sk, aad)


# ─── String-level wrappers (base64 of v7 binary) ──────────────────────────────────
# Ciphertext string format v7:
#   base64( nonce || masked_blob || auth_tag )
# Entirely printable ASCII; 0-3 trailing '=' pad chars possible.
# noise_p is HMAC-derived from key+nonce — never stored in the ciphertext.
# Backward-compatible: legacy v6/v5/v3/v2 strings remain decodable with opt-in.

def encrypt_str(message: str, key: list[int], aad: bytes = b"") -> str:
    """Encrypt *message* and return a base64-encoded v7 ciphertext string.

    The string is safe for any ASCII-compatible text channel.  Use
    ``encrypt_bytes`` directly when the transport channel is binary-safe.
    """
    return base64.b64encode(encrypt_bytes(message, key, aad=aad)).decode('ascii')


def decrypt_str(cypher: str, key: list[int], aad: bytes = b"",
                allow_legacy_unauthenticated: bool = False,
                legacy_v6_varint: bool = False) -> str:
    """Decrypt a ciphertext string produced by ``encrypt_str``.

    Accepts:
      v7  — base64-encoded authenticated binary blob, fixed-width tokens (no colon, default).
      v6  — base64-encoded authenticated binary blob, legacy LEB128 tokens
            (no colon; pass ``legacy_v6_varint=True``, see CVF1).
      v5  — base64-encoded unauthenticated binary blob (legacy, opt-in).
      v3  — ``<nonce_hex>:<noise_p_hex>:<b128_tokens_hex>`` (colon-separated).
      v2  — ``<nonce_hex>:<noise_p_hex>:<space-separated decimals>`` (legacy).
    """
    if ":" not in cypher:
        return decrypt_bytes(base64.b64decode(cypher), key, aad=aad,
                             allow_legacy_unauthenticated=allow_legacy_unauthenticated,
                             legacy_v6_varint=legacy_v6_varint)
    # Legacy v2/v3 path — requires explicit opt-in, same policy as v5.
    if not allow_legacy_unauthenticated:
        raise ValueError(
            "Ciphertext appears to be a legacy v2/v3 colon-delimited format. "
            "These formats carry no integrity protection. To decode them, set "
            "allow_legacy_unauthenticated=True."
        )
    try:
        nonce_hex, noise_p_hex, token_field = cypher.split(":", 2)
    except ValueError:
        raise ValueError(
            "Malformed ciphertext — expected base64 (v6/v5) or "
            "'<nonce_hex>:<noise_p_hex>:<tokens>' (v2/v3)."
        )
    nonce   = bytes.fromhex(nonce_hex)
    noise_p = int(noise_p_hex, 16) / 255.0
    if ' ' in token_field:
        tokens = [int(t) for t in token_field.split()]          # v2
    else:
        tokens = _b128_decode_tokens(bytes.fromhex(token_field))  # v3
    # Use the noise_p stored in the legacy ciphertext (HMAC derivation was
    # introduced in v5; v2/v3 ciphertexts carry their own stored noise_p).
    return "".join(chr(c) for c in _decrypt_with_noise_p(nonce, tokens, key, noise_p))


# ─── Streaming encrypt / decrypt ─────────────────────────────────────────────
# Wire format: nonce (16 B) || varint-encoded tokens || HMAC-SHA256 tag (32 B).
# Identical to the v6 binary layout but without block padding — plaintext
# length is not hidden.  Use the block API when length obfuscation is required.
# encrypt_stream / decrypt_stream are their own round-trip pair and are not
# cross-compatible with encrypt_bytes / decrypt_bytes (padding differs).

def encrypt_stream(
    plaintext: Iterable[str],
    key: list[int],
    aad: bytes = b"",
) -> Generator[bytes, None, None]:
    """Yield nonce, per-character token bytes, then HMAC-SHA256 auth tag.

    Wire layout: nonce (16 B) || varint token bytes || auth tag (32 B).
    No block padding is applied — use encrypt_bytes when length obfuscation
    is required.  Decryption must use decrypt_stream.
    """
    _validate_key(key)
    nonce = secrets.token_bytes(_NONCE_SIZE)
    kb = _key_bytes(key)
    noise_p = _derive_noise_p(kb, nonce)
    K = len(key)

    h = hmac.new(kb, digestmod=hashlib.sha256)
    h.update(b'\x03' + len(aad).to_bytes(4, 'big') + aad + nonce)

    yield nonce

    ct_pos = 0
    real_idx = 0
    ks_gen = _varint_keystream_blocks(kb, nonce)
    ks_buf: bytearray = bytearray()

    for char in plaintext:
        c = ord(char)
        buf = bytearray()
        while True:
            if _is_noise_pos(kb, nonce, ct_pos, noise_p):
                k = key[real_idx % K]
                noise_c = _derive_noise_char(kb, nonce, ct_pos)
                noise_add = _derive_noise_token_addend(kb, nonce, ct_pos, k)
                buf.extend(_b128_encode_token(noise_c * k + noise_add))
                ct_pos += 1
            else:
                k = key[real_idx % K]
                addend = _derive_addend(kb, nonce, real_idx, k)
                buf.extend(_b128_encode_token(c * k + addend))
                ct_pos += 1
                real_idx += 1
                break
        chunk = bytes(buf)
        while len(ks_buf) < len(chunk):
            ks_buf.extend(next(ks_gen))
        masked = bytes(a ^ b for a, b in zip(chunk, ks_buf[:len(chunk)]))
        del ks_buf[:len(chunk)]
        h.update(masked)
        yield masked

    yield h.digest()


def decrypt_stream(
    byte_chunks: Iterable[bytes],
    key: list[int],
    aad: bytes = b"",
    *,
    enable_unauthenticated_streaming: bool = False,
) -> Generator[str, None, None]:
    """Decrypt a byte stream produced by encrypt_stream; yield plaintext chars.

    The last 32 bytes are buffered to isolate the HMAC auth tag.  **Plaintext
    characters are yielded before the tag is verified** (release of
    unverified plaintext, RUP). This API is therefore unsafe by default;
    callers must opt in via ``enable_unauthenticated_streaming=True`` to
    acknowledge the RUP semantics.

    For most use cases prefer :func:`decrypt_stream_strict`, which buffers
    all decrypted plaintext and verifies the tag before returning.

    Raises ValueError on truncated input or authentication failure (the auth
    failure is raised after all plaintext has already been yielded).
    """
    if not enable_unauthenticated_streaming:
        raise ValueError(
            "decrypt_stream releases plaintext before the auth tag is "
            "verified (RUP). Pass enable_unauthenticated_streaming=True to "
            "acknowledge this, or use decrypt_stream_strict to buffer + "
            "verify before any plaintext is returned."
        )
    _validate_key(key)
    kb = _key_bytes(key)
    chunk_iter = iter(byte_chunks)

    # Phase 1: read nonce from the head of the stream
    nonce_buf = bytearray()
    for chunk in chunk_iter:
        nonce_buf.extend(chunk)
        if len(nonce_buf) >= _NONCE_SIZE:
            leftover = bytes(nonce_buf[_NONCE_SIZE:])
            nonce = bytes(nonce_buf[:_NONCE_SIZE])
            break
    else:
        raise ValueError(
            f"Stream truncated: nonce incomplete "
            f"({len(nonce_buf)}/{_NONCE_SIZE} bytes)."
        )

    noise_p = _derive_noise_p(kb, nonce)
    K = len(key)
    h = hmac.new(kb, digestmod=hashlib.sha256)
    h.update(b'\x03' + len(aad).to_bytes(4, 'big') + aad + nonce)

    tail = bytearray(leftover)
    varint_buf: bytearray = bytearray()
    ct_pos = 0
    real_idx = 0
    ks_gen = _varint_keystream_blocks(kb, nonce)
    ks_buf: bytearray = bytearray()

    def _drain(data: bytes) -> Generator[str, None, None]:
        nonlocal ct_pos, real_idx
        h.update(data)
        while len(ks_buf) < len(data):
            ks_buf.extend(next(ks_gen))
        unmasked = bytes(a ^ b for a, b in zip(data, ks_buf[:len(data)]))
        del ks_buf[:len(data)]
        for b in unmasked:
            varint_buf.append(b)
            if not (b & 0x80):
                value = 0
                shift = 0
                for vb in varint_buf:
                    value |= (vb & 0x7F) << shift
                    shift += 7
                varint_buf.clear()
                if not _is_noise_pos(kb, nonce, ct_pos, noise_p):
                    k = key[real_idx % K]
                    addend = _derive_addend(kb, nonce, real_idx, k)
                    yield chr((value - addend) // k)
                    real_idx += 1
                ct_pos += 1

    # Phase 2: slide through chunks, keeping last _TAG_SIZE bytes in tail
    for chunk in chunk_iter:
        tail.extend(chunk)
        safe_len = len(tail) - _TAG_SIZE
        if safe_len > 0:
            yield from _drain(bytes(tail[:safe_len]))
            del tail[:safe_len]

    # Phase 3: split tail into body remainder and auth tag
    if len(tail) < _TAG_SIZE:
        raise ValueError(
            f"Stream truncated: need {_TAG_SIZE}-byte auth tag, "
            f"only {len(tail)} bytes remain."
        )

    body_remainder = bytes(tail[:-_TAG_SIZE])
    recv_tag = bytes(tail[-_TAG_SIZE:])

    if body_remainder:
        yield from _drain(body_remainder)

    # Phase 4: verify auth tag
    if not hmac.compare_digest(h.digest(), recv_tag):
        raise ValueError("Authentication failed: invalid HMAC tag.")


def decrypt_stream_strict(
    byte_chunks: Iterable[bytes],
    key: list[int],
    aad: bytes = b"",
) -> str:
    """Authenticated streaming decrypt: buffer all plaintext, verify, return.

    Consumes the full ``byte_chunks`` iterable, verifies the HMAC-SHA256
    auth tag, and only then returns the joined plaintext string. No partial
    plaintext escapes this function on authentication failure.

    Use this in preference to :func:`decrypt_stream` whenever the consumer
    cannot tolerate seeing unverified plaintext (i.e. nearly always).
    """
    chars: list[str] = []
    gen = decrypt_stream(
        byte_chunks, key, aad,
        enable_unauthenticated_streaming=True,
    )
    for ch in gen:
        chars.append(ch)
    return "".join(chars)


# ─── Streaming AE (online authenticated encryption) ──────────────────────────
# Wire format (v6s-ae):
#   nonce (16 B)
#   || for each chunk i:
#      uint32_be(chunk_len) || masked_blob_chunk || chunk_tag (32 B)
#   || sentinel: uint32_be(0) || final_tag (32 B)
#
# chunk_tag  = HMAC(key_bytes, b'\x08' || uint32_be(len(aad)) || aad
#                              || nonce || uint32_be(i) || masked_chunk)
# final_tag  = HMAC(key_bytes, b'\x09' || uint32_be(len(aad)) || aad
#                              || nonce || uint32_be(N))   # N = total chunks
#
# Domain bytes 0x08 and 0x09 are reserved exclusively for streaming AE and
# do not overlap with any other derivation domain (see SPEC.md §3.7).
#
# Security properties:
# • No RUP: plaintext from chunk i is yielded only after chunk i's tag passes.
# • Reorder-safe: chunk index is bound into each tag.
# • Truncation-safe: final_tag binds the total chunk count N; a stream cut
#   before the sentinel causes final_tag verification to fail.
# • AAD-bound: every tag commits to the same AAD.
# • The domain-0x07 XOR keystream is cumulative across chunks (same generator
#   state as encrypt_stream) so masked bytes are identical for equal inputs.

#: Default chunk size (bytes of masked_blob) for :func:`encrypt_stream_ae`.
STREAM_AE_CHUNK_SIZE = 1024


def encrypt_stream_ae(
    plaintext: Iterable[str],
    key: list[int],
    aad: bytes = b"",
    chunk_size: int = STREAM_AE_CHUNK_SIZE,
) -> Generator[bytes, None, None]:
    """Yield an online-authenticated encrypted stream (v6s-ae format).

    Wire layout::

        nonce (16 B)
        [uint32_be(len) || masked_chunk || chunk_tag(32 B)] × N
        uint32_be(0) || final_tag(32 B)

    Each chunk is tagged with HMAC-SHA256 before being yielded.
    :func:`decrypt_stream_ae` verifies each chunk's tag before releasing its
    plaintext, providing online AE semantics with no RUP (fixes CAV-001).

    *chunk_size* controls the granularity of per-chunk tagging (bytes of
    masked_blob per frame, default 1024). Smaller values reduce per-chunk
    latency at the cost of more tag overhead.

    Use :func:`decrypt_stream_ae` to decrypt; not cross-compatible with
    :func:`decrypt_stream`.
    """
    _validate_key(key)
    nonce = secrets.token_bytes(_NONCE_SIZE)
    kb = _key_bytes(key)
    noise_p = _derive_noise_p(kb, nonce)
    K = len(key)
    aad_len4 = len(aad).to_bytes(4, 'big')

    yield nonce

    ct_pos = 0
    real_idx = 0
    ks_gen = _varint_keystream_blocks(kb, nonce)
    ks_buf: bytearray = bytearray()
    pending_masked: bytearray = bytearray()
    chunk_idx = 0

    def _flush_chunk(data: bytes) -> bytes:
        tag = hmac.new(
            kb,
            b'\x08' + nonce + aad_len4 + aad + chunk_idx.to_bytes(4, 'big') + data,
            hashlib.sha256,
        ).digest()
        return len(data).to_bytes(4, 'big') + data + tag

    for char in plaintext:
        c = ord(char)
        buf = bytearray()
        while True:
            if _is_noise_pos(kb, nonce, ct_pos, noise_p):
                k = key[real_idx % K]
                noise_c = _derive_noise_char(kb, nonce, ct_pos)
                noise_add = _derive_noise_token_addend(kb, nonce, ct_pos, k)
                buf.extend(_b128_encode_token(noise_c * k + noise_add))
                ct_pos += 1
            else:
                k = key[real_idx % K]
                addend = _derive_addend(kb, nonce, real_idx, k)
                buf.extend(_b128_encode_token(c * k + addend))
                ct_pos += 1
                real_idx += 1
                break
        raw = bytes(buf)
        while len(ks_buf) < len(raw):
            ks_buf.extend(next(ks_gen))
        masked = bytes(a ^ b for a, b in zip(raw, ks_buf[:len(raw)]))
        del ks_buf[:len(raw)]
        pending_masked.extend(masked)

        while len(pending_masked) >= chunk_size:
            frame_data = bytes(pending_masked[:chunk_size])
            del pending_masked[:chunk_size]
            yield _flush_chunk(frame_data)
            chunk_idx += 1

    if pending_masked:
        yield _flush_chunk(bytes(pending_masked))
        chunk_idx += 1

    # Sentinel frame: zero-length body + final tag binding total chunk count
    final_tag = hmac.new(
        kb,
        b'\x09' + nonce + aad_len4 + aad + chunk_idx.to_bytes(4, 'big'),
        hashlib.sha256,
    ).digest()
    yield (0).to_bytes(4, 'big') + final_tag


def decrypt_stream_ae(
    byte_chunks: Iterable[bytes],
    key: list[int],
    aad: bytes = b"",
) -> Generator[str, None, None]:
    """Decrypt a stream produced by :func:`encrypt_stream_ae`; yield plaintext chars.

    Each chunk's HMAC-SHA256 tag is verified **before** any of its plaintext
    characters are yielded — no unverified plaintext is ever released (online
    AE semantics, fixes CAV-001).  The final sentinel tag additionally
    authenticates the total chunk count, so a truncated stream is detected
    when the generator is exhausted.

    Raises ``ValueError`` on:
    - any chunk tag mismatch,
    - final sentinel tag mismatch,
    - stream truncation (missing bytes anywhere).
    """
    _validate_key(key)
    kb = _key_bytes(key)
    aad_len4 = len(aad).to_bytes(4, 'big')

    chunk_iter = iter(byte_chunks)
    _buf: bytearray = bytearray()

    def _read_n(n: int) -> bytes:
        while len(_buf) < n:
            try:
                _buf.extend(next(chunk_iter))
            except StopIteration:
                raise ValueError(
                    f"Stream truncated: need {n} bytes, "
                    f"only {len(_buf)} available."
                )
        data = bytes(_buf[:n])
        del _buf[:n]
        return data

    nonce = _read_n(_NONCE_SIZE)
    noise_p = _derive_noise_p(kb, nonce)
    K = len(key)
    ct_pos = 0
    real_idx = 0
    ks_gen = _varint_keystream_blocks(kb, nonce)
    ks_buf: bytearray = bytearray()
    varint_buf: bytearray = bytearray()
    chunk_idx = 0

    while True:
        chunk_len = int.from_bytes(_read_n(4), 'big')

        if chunk_len == 0:
            # Sentinel frame — verify final tag and finish
            recv_final = _read_n(_TAG_SIZE)
            expected_final = hmac.new(
                kb,
                b'\x09' + nonce + aad_len4 + aad + chunk_idx.to_bytes(4, 'big'),
                hashlib.sha256,
            ).digest()
            if not hmac.compare_digest(recv_final, expected_final):
                raise ValueError("Authentication failed: invalid final tag.")
            return

        masked_chunk = _read_n(chunk_len)
        recv_chunk_tag = _read_n(_TAG_SIZE)

        expected_chunk_tag = hmac.new(
            kb,
            b'\x08' + nonce + aad_len4 + aad
            + chunk_idx.to_bytes(4, 'big') + masked_chunk,
            hashlib.sha256,
        ).digest()
        if not hmac.compare_digest(recv_chunk_tag, expected_chunk_tag):
            raise ValueError(
                f"Authentication failed: invalid tag on chunk {chunk_idx}."
            )

        # Tag verified — safe to unmask and yield plaintext from this chunk
        while len(ks_buf) < chunk_len:
            ks_buf.extend(next(ks_gen))
        unmasked = bytes(a ^ b for a, b in zip(masked_chunk, ks_buf[:chunk_len]))
        del ks_buf[:chunk_len]

        for b in unmasked:
            varint_buf.append(b)
            if not (b & 0x80):
                value = 0
                shift = 0
                for vb in varint_buf:
                    value |= (vb & 0x7F) << shift
                    shift += 7
                varint_buf.clear()
                if not _is_noise_pos(kb, nonce, ct_pos, noise_p):
                    k = key[real_idx % K]
                    addend = _derive_addend(kb, nonce, real_idx, k)
                    yield chr((value - addend) // k)
                    real_idx += 1
                ct_pos += 1

        chunk_idx += 1