"""pytest test suite for NAPSEQ v6 Known-Answer Test vectors.

Loads tests/kat/v6_vectors.json (generated by tests/gen_kats.py) and
verifies:
  - Positive vectors: encrypt_bytes produces byte-identical ciphertext_hex,
    and decrypt_bytes / decrypt_str round-trips correctly.
  - Negative vectors: decrypt_bytes raises ValueError containing the
    expected_exception substring.

Run:
    pytest tests/test_kats.py -v
"""

import base64
import json
import os
import sys

import pytest

# Make napqes importable from repo root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import napqes  # noqa: E402
from tests.gen_kats import _encrypt_with_nonce  # noqa: E402

_VECTORS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "kat", "v6_vectors.json"
)


# ---------------------------------------------------------------------------
# Load vectors
# ---------------------------------------------------------------------------

def _load_vectors():
    with open(_VECTORS_PATH, encoding="utf-8") as f:
        data = json.load(f)
    return data["vectors"]


_ALL_VECTORS = _load_vectors()
_POSITIVE = [v for v in _ALL_VECTORS if v["kind"] == "positive"]
_NEGATIVE = [v for v in _ALL_VECTORS if v["kind"] == "negative"]


# ---------------------------------------------------------------------------
# Positive vector tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_encrypt_bytes_deterministic(vec):
    """encrypt_bytes with the stored nonce must produce byte-identical output."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    expected_ct = bytes.fromhex(vec["ciphertext_hex"])
    nonce_hex = vec["nonce_hex"]

    if not message:
        # Empty message: expect empty ciphertext
        assert napqes.encrypt_bytes("", key, aad=aad) == b""
        assert expected_ct == b""
        return

    nonce = bytes.fromhex(nonce_hex)
    ct = _encrypt_with_nonce(message, key, nonce, aad=aad)
    assert ct == expected_ct, (
        f"[{vec['id']}] ciphertext mismatch.\n"
        f"  expected: {expected_ct.hex()}\n"
        f"  got:      {ct.hex()}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_decrypt_roundtrip(vec):
    """decrypt_bytes of the stored ciphertext_hex must recover the message."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    ct = bytes.fromhex(vec["ciphertext_hex"])

    if not message:
        assert napqes.decrypt_bytes(ct, key, aad=aad) == ""
        return

    plaintext = napqes.decrypt_bytes(ct, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] roundtrip failed: got {plaintext!r}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_decrypt_str_roundtrip(vec):
    """decrypt_str of base64(ciphertext_hex) must recover the message."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    ct = bytes.fromhex(vec["ciphertext_hex"])

    if not message:
        assert napqes.decrypt_str("", key, aad=aad) == ""
        return

    ct_b64 = base64.b64encode(ct).decode("ascii")
    plaintext = napqes.decrypt_str(ct_b64, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] decrypt_str roundtrip failed: got {plaintext!r}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_encrypt_str_roundtrip(vec):
    """encrypt_str / decrypt_str round-trip using the live random nonce path."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])

    if not message:
        ct_b64 = napqes.encrypt_str("", key, aad=aad)
        assert ct_b64 == ""
        return

    ct_b64 = napqes.encrypt_str(message, key, aad=aad)
    plaintext = napqes.decrypt_str(ct_b64, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] encrypt_str/decrypt_str roundtrip failed: got {plaintext!r}"
    )


# ---------------------------------------------------------------------------
# Negative vector tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("vec", _NEGATIVE, ids=[v["id"] for v in _NEGATIVE])
def test_negative_raises_value_error(vec):
    """Tampered / invalid ciphertexts must raise ValueError with expected message."""
    key = vec["key"]
    aad = bytes.fromhex(vec["aad_hex"])
    tampered = bytes.fromhex(vec["tampered_hex"])
    expected_msg = vec["expected_exception"]
    allow_legacy = vec.get("allow_legacy_unauthenticated", False)

    with pytest.raises(ValueError, match=expected_msg):
        napqes.decrypt_bytes(
            tampered, key, aad=aad,
            allow_legacy_unauthenticated=allow_legacy,
        )


# ---------------------------------------------------------------------------
# Cross-implementation deterministism check
# ---------------------------------------------------------------------------

def test_gen_kats_check_mode():
    """gen_kats.py --check must pass: regenerated vectors match checked-in file."""
    import subprocess
    result = subprocess.run(
        [sys.executable, "tests/gen_kats.py", "--check"],
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    assert result.returncode == 0, (
        "gen_kats.py --check failed:\n" + result.stdout + result.stderr
    )
