"""pytest test suite for NAPSEQ v6 Known-Answer Test vectors.

Loads tests/kat/v6_vectors.json (generated by tests/gen_kats.py) and
verifies:
  - Positive vectors: encrypt_bytes produces byte-identical ciphertext_hex,
    and decrypt_bytes / decrypt_str round-trips correctly.
  - Negative vectors: decrypt_bytes raises ValueError containing the
    expected_exception substring.

Run:
    pytest tests/test_kats.py -v
"""

import base64
import json
import os
import sys

import pytest

# Make napqes importable from repo root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import napqes  # noqa: E402
from tests.gen_kats import _encrypt_with_nonce  # noqa: E402

_VECTORS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "kat", "v6_vectors.json"
)


# ---------------------------------------------------------------------------
# Load vectors
# ---------------------------------------------------------------------------

def _load_vectors():
    with open(_VECTORS_PATH, encoding="utf-8") as f:
        data = json.load(f)
    return data["vectors"]


_ALL_VECTORS = _load_vectors()
_POSITIVE = [v for v in _ALL_VECTORS
             if v["kind"] == "positive" and v.get("api") != "stream_ae"]
_NEGATIVE = [v for v in _ALL_VECTORS
             if v["kind"] == "negative" and v.get("api") != "stream_ae"]
_STREAM_AE_POSITIVE = [v for v in _ALL_VECTORS
                       if v["kind"] == "positive" and v.get("api") == "stream_ae"]
_STREAM_AE_NEGATIVE = [v for v in _ALL_VECTORS
                       if v["kind"] == "negative" and v.get("api") == "stream_ae"]


# ---------------------------------------------------------------------------
# Positive vector tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_encrypt_bytes_deterministic(vec):
    """encrypt_bytes with the stored nonce must produce byte-identical output."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    expected_ct = bytes.fromhex(vec["ciphertext_hex"])
    nonce_hex = vec["nonce_hex"]

    nonce = bytes.fromhex(nonce_hex)
    ct = _encrypt_with_nonce(message, key, nonce, aad=aad)
    assert ct == expected_ct, (
        f"[{vec['id']}] ciphertext mismatch.\n"
        f"  expected: {expected_ct.hex()}\n"
        f"  got:      {ct.hex()}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_decrypt_roundtrip(vec):
    """decrypt_bytes of the stored ciphertext_hex must recover the message."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    ct = bytes.fromhex(vec["ciphertext_hex"])

    plaintext = napqes.decrypt_bytes(ct, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] roundtrip failed: got {plaintext!r}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_decrypt_str_roundtrip(vec):
    """decrypt_str of base64(ciphertext_hex) must recover the message."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    ct = bytes.fromhex(vec["ciphertext_hex"])

    ct_b64 = base64.b64encode(ct).decode("ascii")
    plaintext = napqes.decrypt_str(ct_b64, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] decrypt_str roundtrip failed: got {plaintext!r}"
    )


@pytest.mark.parametrize("vec", _POSITIVE, ids=[v["id"] for v in _POSITIVE])
def test_positive_encrypt_str_roundtrip(vec):
    """encrypt_str / decrypt_str round-trip using the live random nonce path."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])


    ct_b64 = napqes.encrypt_str(message, key, aad=aad)
    plaintext = napqes.decrypt_str(ct_b64, key, aad=aad)
    assert plaintext == message, (
        f"[{vec['id']}] encrypt_str/decrypt_str roundtrip failed: got {plaintext!r}"
    )


# ---------------------------------------------------------------------------
# Negative vector tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("vec", _NEGATIVE, ids=[v["id"] for v in _NEGATIVE])
def test_negative_raises_value_error(vec):
    """Tampered / invalid ciphertexts must raise ValueError with expected message."""
    key = vec["key"]
    aad = bytes.fromhex(vec["aad_hex"])
    tampered = bytes.fromhex(vec["tampered_hex"])
    expected_msg = vec["expected_exception"]
    allow_legacy = vec.get("allow_legacy_unauthenticated", False)

    with pytest.raises(ValueError, match=expected_msg):
        napqes.decrypt_bytes(
            tampered, key, aad=aad,
            allow_legacy_unauthenticated=allow_legacy,
        )


# ---------------------------------------------------------------------------
# Cross-implementation deterministism check
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# CF-001 regression: v2/v3 colon-delimited path must honour allow_legacy_unauthenticated
# ---------------------------------------------------------------------------

def test_decrypt_str_rejects_v2v3_without_flag():
    """decrypt_str must refuse v2/v3 colon-delimited ciphertext when flag is False (default)."""
    key = [1031, 1033, 1039, 1049]
    # Syntactically valid v2 ciphertext: nonce_hex:noise_p_hex:space-separated tokens
    fake_v2 = "aabbccddaabbccddaabbccddaabbccdd:ff:72 69 6e 67"
    with pytest.raises(ValueError, match="allow_legacy_unauthenticated"):
        napqes.decrypt_str(fake_v2, key)


def test_decrypt_str_rejects_v2v3_with_flag_false_explicit():
    """Explicit allow_legacy_unauthenticated=False must also block v2/v3 path."""
    key = [1031, 1033, 1039, 1049]
    fake_v2 = "aabbccddaabbccddaabbccddaabbccdd:ff:72 69 6e 67"
    with pytest.raises(ValueError, match="allow_legacy_unauthenticated"):
        napqes.decrypt_str(fake_v2, key, allow_legacy_unauthenticated=False)


def test_decrypt_str_accepts_v2v3_with_flag_true():
    """allow_legacy_unauthenticated=True must allow the v2/v3 path to proceed past the flag check."""
    key = [1031, 1033, 1039, 1049]
    # Syntactically invalid tokens — we just want to confirm the flag check is passed;
    # the subsequent parse/decode may raise for other reasons.
    fake_v2 = "aabbccddaabbccddaabbccddaabbccdd:ff:72 69 6e 67"
    try:
        napqes.decrypt_str(fake_v2, key, allow_legacy_unauthenticated=True)
    except ValueError as exc:
        assert "allow_legacy_unauthenticated" not in str(exc), (
            "Flag-check error should not appear when flag is True; "
            f"got: {exc}"
        )


# ---------------------------------------------------------------------------
# Cross-implementation determinism check
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# MF-006: Key serialization – 5-byte fixed-width encoding KATs
# ---------------------------------------------------------------------------

_KEY_BYTES_KATS = [
    # (description, key, expected_hex)
    # Trivial cases — verifiable by inspection.
    ("single prime [2]",  [2], "0000000002"),
    ("single prime [3]",  [3], "0000000003"),
    ("two-element [2, 3]", [2, 3], "00000000020000000003"),
    # KEY_1 = [7_999_993 = 0x7A11F9]
    ("KEY_1 [7_999_993]", [7_999_993], "00007a11f9"),
    # KEY_4 individual elements (1_000_003 = 0x0F4243, etc.)
    ("KEY_4[0] [1_000_003]", [1_000_003], "00000f4243"),
    ("KEY_4[1] [1_000_033]", [1_000_033], "00000f4261"),
    ("KEY_4[2] [1_000_037]", [1_000_037], "00000f4265"),
    ("KEY_4[3] [1_000_039]", [1_000_039], "00000f4267"),
    # Full KEY_4 — verifies element concatenation order
    (
        "KEY_4 full [1_000_003, 1_000_033, 1_000_037, 1_000_039]",
        [1_000_003, 1_000_033, 1_000_037, 1_000_039],
        "00000f424300000f426100000f426500000f4267",
    ),
]


@pytest.mark.parametrize(
    "desc,key,expected_hex",
    _KEY_BYTES_KATS,
    ids=[row[0] for row in _KEY_BYTES_KATS],
)
def test_key_bytes_serialization(desc, key, expected_hex):
    """_key_bytes must produce 5-byte big-endian encoding for each key element."""
    result = napqes._key_bytes(key)
    assert result.hex() == expected_hex, (
        f"{desc}: expected {expected_hex!r}, got {result.hex()!r}"
    )


# ---------------------------------------------------------------------------
# MF-003: Zero-length key must raise ValueError, not ZeroDivisionError
# ---------------------------------------------------------------------------

_DUMMY_NONCE  = b'\x00' * 16
_DUMMY_CT     = bytes(64)   # 48 B min for v6 auth tag; 64 is safe
_DUMMY_CT_B64 = base64.b64encode(_DUMMY_CT).decode()


def test_mf003_encrypt_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.encrypt([65], [])


def test_mf003_decrypt_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes._decrypt(_DUMMY_NONCE, [65], [])


def test_mf003_encrypt_bytes_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.encrypt_bytes("a", [])


def test_mf003_decrypt_bytes_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.decrypt_bytes(_DUMMY_CT, [])


def test_mf003_encrypt_str_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.encrypt_str("a", [])


def test_mf003_decrypt_str_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.decrypt_str(_DUMMY_CT_B64, [])


def test_mf003_encrypt_stream_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        next(napqes.encrypt_stream(["a"], []))


def test_mf003_decrypt_stream_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        next(napqes.decrypt_stream(
            [_DUMMY_CT], [],
            enable_unauthenticated_streaming=True,
        ))


def test_mf003_decrypt_stream_strict_empty_key():
    with pytest.raises(ValueError, match="non-empty"):
        napqes.decrypt_stream_strict([_DUMMY_CT], [])


# ---------------------------------------------------------------------------
# Streaming AE KAT tests (encrypt_stream_ae / decrypt_stream_ae)
# ---------------------------------------------------------------------------

from tests.gen_kats import _encrypt_stream_ae_with_nonce  # noqa: E402


@pytest.mark.parametrize(
    "vec", _STREAM_AE_POSITIVE, ids=[v["id"] for v in _STREAM_AE_POSITIVE]
)
def test_stream_ae_positive_deterministic(vec):
    """encrypt_stream_ae with the stored nonce must produce byte-identical output."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    nonce = bytes.fromhex(vec["nonce_hex"])
    expected_ct = bytes.fromhex(vec["full_ciphertext_hex"])
    chunk_size = vec.get("chunk_size", napqes.STREAM_AE_CHUNK_SIZE)

    got = _encrypt_stream_ae_with_nonce(message, key, nonce, aad, chunk_size)
    assert got == expected_ct, (
        f"[{vec['id']}] streaming AE ciphertext mismatch.\n"
        f"  expected: {expected_ct.hex()}\n"
        f"  got:      {got.hex()}"
    )


@pytest.mark.parametrize(
    "vec", _STREAM_AE_POSITIVE, ids=[v["id"] for v in _STREAM_AE_POSITIVE]
)
def test_stream_ae_positive_decrypt_roundtrip(vec):
    """decrypt_stream_ae of full_ciphertext_hex must recover the message."""
    key = vec["key"]
    message = vec["message"]
    aad = bytes.fromhex(vec["aad_hex"])
    full_ct = bytes.fromhex(vec["full_ciphertext_hex"])

    recovered = "".join(napqes.decrypt_stream_ae(iter([full_ct]), key, aad))
    assert recovered == message, (
        f"[{vec['id']}] streaming AE roundtrip failed: got {recovered!r}"
    )


@pytest.mark.parametrize(
    "vec", _STREAM_AE_NEGATIVE, ids=[v["id"] for v in _STREAM_AE_NEGATIVE]
)
def test_stream_ae_negative_raises(vec):
    """Tampered streaming AE ciphertexts must raise ValueError."""
    key = vec["key"]
    aad = bytes.fromhex(vec["aad_hex"])
    tampered = bytes.fromhex(vec["tampered_hex"])
    expected_msg = vec.get("expected_exception", "")

    with pytest.raises(ValueError, match=expected_msg):
        list(napqes.decrypt_stream_ae(iter([tampered]), key, aad))


def test_gen_kats_check_mode():
    """gen_kats.py --check must pass: regenerated vectors match checked-in file."""
    import subprocess
    result = subprocess.run(
        [sys.executable, "tests/gen_kats.py", "--check"],
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    assert result.returncode == 0, (
        "gen_kats.py --check failed:\n" + result.stdout + result.stderr
    )


def test_stream_ae_vectors_loaded():
    """_STREAM_AE_POSITIVE must contain at least 4 vectors so that streaming-AE
    security claims are always backed by KAT evidence.  A regression that
    accidentally removes stream_ae vectors from v6_vectors.json will be caught
    here immediately rather than silently skipping the parametrised tests."""
    assert len(_STREAM_AE_POSITIVE) >= 4, (
        f"Expected ≥4 streaming-AE positive KAT vectors in v6_vectors.json; "
        f"found {len(_STREAM_AE_POSITIVE)}.  "
        f"Run 'python tests/gen_kats.py' to regenerate."
    )
    assert len(_STREAM_AE_NEGATIVE) >= 2, (
        f"Expected ≥2 streaming-AE negative KAT vectors; "
        f"found {len(_STREAM_AE_NEGATIVE)}."
    )


# ---------------------------------------------------------------------------
# v8 KAT vectors (tests/kat/v8_vectors.json, generated by gen_kats_v8.py)
#
# v8 encryption is deterministic in (primes, sk, aad, message) — the nonce is
# a synthetic IV — so these vectors pin the *public* API byte-for-byte and are
# the reference corpus every other language implementation must reproduce.
# They exist because the v7 corpus above does not exercise v8 at all, which is
# how the Rust port's missing domain-0x0B format subkey went undetected
# (docs/CAVEATS.md, V3-CVF1 Residual 4).
# ---------------------------------------------------------------------------

_V8_VECTORS_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "kat", "v8_vectors.json"
)


def _load_v8_vectors():
    with open(_V8_VECTORS_PATH, encoding="utf-8") as f:
        return json.load(f)["vectors"]


_V8_ALL = _load_v8_vectors()
_V8_POSITIVE = [v for v in _V8_ALL if v["kind"] == "positive"]
_V8_NEGATIVE = [v for v in _V8_ALL if v["kind"] == "negative"]


@pytest.mark.parametrize("vec", _V8_POSITIVE, ids=[v["id"] for v in _V8_POSITIVE])
def test_v8_positive_encrypt_deterministic(vec):
    """encrypt_bytes_v8 must reproduce the stored ciphertext byte-for-byte."""
    ct = napqes.encrypt_bytes_v8(
        vec["message"],
        vec["key"],
        bytes.fromhex(vec["sk_hex"]),
        aad=bytes.fromhex(vec["aad_hex"]),
    )
    assert ct.hex() == vec["ciphertext_hex"], f"{vec['id']}: v8 ciphertext mismatch"


@pytest.mark.parametrize("vec", _V8_POSITIVE, ids=[v["id"] for v in _V8_POSITIVE])
def test_v8_positive_decrypt_roundtrip(vec):
    """decrypt_bytes_v8 must recover the plaintext from the stored ciphertext."""
    pt = napqes.decrypt_bytes_v8(
        bytes.fromhex(vec["ciphertext_hex"]),
        vec["key"],
        bytes.fromhex(vec["sk_hex"]),
        aad=bytes.fromhex(vec["aad_hex"]),
    )
    assert pt == vec["message"], f"{vec['id']}: v8 roundtrip mismatch"


@pytest.mark.parametrize("vec", _V8_NEGATIVE, ids=[v["id"] for v in _V8_NEGATIVE])
def test_v8_negative_raises(vec):
    """Tampered / mis-keyed v8 ciphertexts must raise ValueError."""
    with pytest.raises(ValueError, match=vec.get("expected_exception", "")):
        napqes.decrypt_bytes_v8(
            bytes.fromhex(vec["tampered_hex"]),
            vec["key"],
            bytes.fromhex(vec["sk_hex"]),
            aad=bytes.fromhex(vec["aad_hex"]),
        )


def test_v8_empty_message_is_not_empty_ciphertext():
    """The empty string must produce a full authenticated v8 ciphertext.

    An implementation that short-circuits ``message == ""`` to empty bytes
    emits an unauthenticated, trivially forgeable "ciphertext" and diverges
    from every other implementation; W001 pins the padded behaviour.
    """
    w001 = next(v for v in _V8_POSITIVE if v["id"] == "W001")
    assert w001["message"] == ""
    ct = bytes.fromhex(w001["ciphertext_hex"])
    assert len(ct) == 2928, f"Expected the 2928-byte v8 minimum, got {len(ct)}"


def test_gen_kats_v8_check_mode():
    """gen_kats_v8.py --check must pass: regenerated vectors match the file."""
    import subprocess
    result = subprocess.run(
        [sys.executable, "tests/gen_kats_v8.py", "--check"],
        capture_output=True,
        text=True,
        cwd=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    )
    assert result.returncode == 0, (
        "gen_kats_v8.py --check failed:\n" + result.stdout + result.stderr
    )
